[package]
name = "lsp-servers"
version = "0.1.0"
edition = "2024"
description = "Provides a list of relevant language servers for a given directory."
license = "MIT OR Apache-2.0"

[dependencies]
walkdir = "2.5.0"
